/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgdiccionario_con_dfs_y_bf;
import java.awt.*;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @authors
 *      Osvaldo Domínguez
 *      Ambar Pang
 *      Joel Ruiz
 *      Guiomar Lara
 *      Randy Urriola
 */
public class Principal extends javax.swing.JFrame {
    public JTextField [] respuestas;
    private Busqueda busqueda = new Busqueda();
    private String raiz = "";
    

    /**
     * Creates new form Principal
     * Se crea el vector de JTextField @respuestas que guardará 
     * las primeras 15 posibles palabras.
     */
    public Principal() {
        initComponents();
        respuestas = new JTextField[]{
        respuesta1, respuesta2, respuesta3, respuesta4, respuesta5,
        respuesta6, respuesta7, respuesta8, respuesta9, respuesta10,
        respuesta11, respuesta12, respuesta13, respuesta14, respuesta15};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpAlgoritmo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPEP = new javax.swing.JRadioButton();
        btnPEM = new javax.swing.JRadioButton();
        tablero = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jtxtfPalabra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        respuesta1 = new javax.swing.JTextField();
        respuesta2 = new javax.swing.JTextField();
        respuesta3 = new javax.swing.JTextField();
        respuesta4 = new javax.swing.JTextField();
        respuesta5 = new javax.swing.JTextField();
        respuesta6 = new javax.swing.JTextField();
        respuesta7 = new javax.swing.JTextField();
        respuesta8 = new javax.swing.JTextField();
        respuesta9 = new javax.swing.JTextField();
        respuesta12 = new javax.swing.JTextField();
        respuesta11 = new javax.swing.JTextField();
        respuesta10 = new javax.swing.JTextField();
        respuesta13 = new javax.swing.JTextField();
        respuesta14 = new javax.swing.JTextField();
        respuesta15 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Algoritmos de Búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btngrpAlgoritmo.add(btnPEP);
        btnPEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPEP.setText("Primero en profundidad");
        btnPEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPEPActionPerformed(evt);
            }
        });

        btngrpAlgoritmo.add(btnPEM);
        btnPEM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPEM.setText("Primero el mejor");
        btnPEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPEMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnPEP)
                .addGap(42, 42, 42)
                .addComponent(btnPEM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPEP)
                    .addComponent(btnPEM))
                .addGap(20, 20, 20))
        );

        tablero.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingrese la palabra a buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jtxtfPalabra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtfPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfPalabraActionPerformed(evt);
            }
        });
        jtxtfPalabra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtfPalabraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtfPalabraKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("<html><p>**Importante: solo se permite un máximo de 5 caracteres por palabra</p>\n<p>para efectuar la búqueda</p>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtfPalabra)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtfPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Palabras válidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        respuesta1.setBackground(java.awt.Color.lightGray);

        respuesta2.setEditable(false);
        respuesta2.setBackground(java.awt.Color.lightGray);

        respuesta3.setEditable(false);
        respuesta3.setBackground(java.awt.Color.lightGray);

        respuesta4.setEditable(false);
        respuesta4.setBackground(java.awt.Color.lightGray);

        respuesta5.setEditable(false);
        respuesta5.setBackground(java.awt.Color.lightGray);

        respuesta6.setEditable(false);
        respuesta6.setBackground(java.awt.Color.lightGray);

        respuesta7.setEditable(false);
        respuesta7.setBackground(java.awt.Color.lightGray);

        respuesta8.setEditable(false);
        respuesta8.setBackground(java.awt.Color.lightGray);

        respuesta9.setEditable(false);
        respuesta9.setBackground(java.awt.Color.lightGray);

        respuesta12.setEditable(false);
        respuesta12.setBackground(java.awt.Color.lightGray);

        respuesta11.setEditable(false);
        respuesta11.setBackground(java.awt.Color.lightGray);

        respuesta10.setEditable(false);
        respuesta10.setBackground(java.awt.Color.lightGray);

        respuesta13.setEditable(false);
        respuesta13.setBackground(java.awt.Color.lightGray);

        respuesta14.setEditable(false);
        respuesta14.setBackground(java.awt.Color.lightGray);

        respuesta15.setEditable(false);
        respuesta15.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(respuesta7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(respuesta8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respuesta9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(respuesta10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(respuesta11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respuesta12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respuesta6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(respuesta13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(respuesta14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respuesta15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Espacio de Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(226, 226, 226)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtfPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfPalabraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtfPalabraActionPerformed

    private void jtxtfPalabraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfPalabraKeyTyped
        // TODO add your handling code here:
        //Se evalúa si está ingresando números, si se ingresa algún número enviará en mensaje de error.
        char val = evt.getKeyChar();
        if(btnPEM.isSelected() || btnPEP.isSelected()){
            if(Character.isDigit(val)){
                getToolkit().beep();
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Sólo puede ingresar letras.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        //Advierte de que no se ha elegido nigún algoritmo de búsqueda
        else{
            JOptionPane.showMessageDialog(rootPane, "Debe elegir un algoritmo de búqueda.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            jtxtfPalabra.setText("");

        }
        //Inicia el arreglo @respuestas cada vez que haya un cambio en el JTextField
        for(int i = 0; i < respuestas.length; i++){
            respuestas[i].setText("");
            respuestas[i].setBackground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_jtxtfPalabraKeyTyped

    private void btnPEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPEPActionPerformed
        // TODO add your handling code here:
        if(jtxtfPalabra.getText().length() > 0){
            Iniciar();
        }
    }//GEN-LAST:event_btnPEPActionPerformed

    private void btnPEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPEMActionPerformed
        // TODO add your handling code here:
        if(jtxtfPalabra.getText().length() > 0){
            Iniciar();
        }
    }//GEN-LAST:event_btnPEMActionPerformed

    private void jtxtfPalabraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtfPalabraKeyReleased
        // TODO add your handling code here:
        raiz = "";
        tablero.removeAll();;
        tablero.setBackground(Color.WHITE);
        //Si el JTextFild contiene alguna letra
        if(btngrpAlgoritmo.getSelection() != null){
            Iniciar();
            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Debe elegir una opción de los algoritmos de búqueda.", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jtxtfPalabraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    //Método que inicia todo el proceso
    public void Iniciar()
    {
        raiz = UltimaPalabra(jtxtfPalabra.getText());
        char inicial = raiz.charAt(0);
        inicial= Character.toLowerCase(inicial);
        //Si la letra inicial de cada palabra no empieza con 'd', 'e' o 'f' enviará un mensaje de advertencia.
        if(inicial == 'd' || inicial == 'e' || inicial == 'f')
        {
            //Verifica que la palabra no tenga má de 5 caracteres.
            if(raiz.length()> 5)
            {
                jtxtfPalabra.setForeground(Color.red);
                JOptionPane.showMessageDialog(rootPane, "Sólo se aceptan palabras con 5 caracteres o menos.", "ERROR", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                jtxtfPalabra.setForeground(Color.BLACK);
                if(btnPEP.isSelected())
                {
                    final long startTime = System.nanoTime();
                    busqueda.Buscar(raiz, 1);
                    busqueda.Imprimir(respuestas);
                    final long duration =System.nanoTime()-startTime;
                    System.out.println("Tiempo de ejecución:"+duration/1000000+("ms"));
                    repaint();
                }
                else if(btnPEM.isSelected())
                {
                    final long startTime = System.nanoTime();
                    busqueda.Buscar(raiz, 2);
                    busqueda.Imprimir(respuestas);
                    final long duration =System.nanoTime()-startTime;
                    System.out.println("Tiempo de ejecución:"+duration/1000000+"ms");
                    repaint();
                   
                }
                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Sólo se aceptan palabras que inicien con 'd', 'e' o 'f'.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }

    //Método que determina cual es la última palabra de la cadena ingresada.
    public String UltimaPalabra(String texto)
    {
        String ultima = null;
        texto.split(texto);
        if(texto.contains(" "))
        {//Si tiene espacio, buscará a partir de la última posición de su espacio.
            ultima = texto.substring(texto.lastIndexOf(" ")+1);
        }
        else
        {
            ultima = texto;
        }
        return ultima;
    }
    
    //Método que pinta el JPanel con los caracteres escritos y sus caracteres hijos.
    public void paint(Graphics g)
    {
        super.paint(g);
        Graphics2D g2d = (Graphics2D)tablero.getGraphics();
        //El rectángulo @r será el que dibuje los cuadros en el JPanel
        Rectangle r = new Rectangle((int)tablero.getBounds().x/3*2, (int)tablero.getBounds().y, 20, 20);
        tablero.removeAll();
        tablero.setBackground(Color.WHITE);
        //En este ciclo For se dibujan todos los caracteres que se han escrito en JTextField
        for(int i = 0; i < raiz.length(); i++)
        {
            char letra = raiz.charAt(i);
            g2d.draw(r);
            g2d.drawString(letra+"", r.x + 6, r.y + 15);
            if(i<raiz.length()-1)
                g2d.drawLine(r.x + 10, r.y + 20, r.x + 10, r.y + 40);
            r.y = r.y + 40;
        }
        String hijos = busqueda.getLetas_Hijo();
        int cant = hijos.length();
        r.y = r.y - 20;
        int x = r.x + 10;
        int y = r.y;
        //En este ciclo For se dibujan todos los caracteres hijos de lo escrito.
        for(int i = 0; i < cant; i++)
        {
            r.x = (int)tablero.getBounds().width/cant*i+12;
            g2d.drawLine(x, y, r.x + 10, r.y + 100);
            g2d.drawRect(r.x, r.y+100, r.width, r.height);
            char letra = hijos.charAt(i);
            g2d.drawString(letra+"", r.x + 6, r.y + 115);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton btnPEM;
    public javax.swing.JRadioButton btnPEP;
    private javax.swing.ButtonGroup btngrpAlgoritmo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField jtxtfPalabra;
    public javax.swing.JTextField respuesta1;
    public javax.swing.JTextField respuesta10;
    public javax.swing.JTextField respuesta11;
    public javax.swing.JTextField respuesta12;
    public javax.swing.JTextField respuesta13;
    public javax.swing.JTextField respuesta14;
    public javax.swing.JTextField respuesta15;
    public javax.swing.JTextField respuesta2;
    public javax.swing.JTextField respuesta3;
    public javax.swing.JTextField respuesta4;
    public javax.swing.JTextField respuesta5;
    public javax.swing.JTextField respuesta6;
    public javax.swing.JTextField respuesta7;
    public javax.swing.JTextField respuesta8;
    public javax.swing.JTextField respuesta9;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
